# Generated by Django 5.2.4 on 2025-08-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это главная аптека', verbose_name='Главная аптека'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='main_pharmacy',
            field=models.ForeignKey(blank=True, help_text='Выберите главную аптеку, если эта аптека является филиалом', limit_choices_to={'is_main': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadr.pharmacy', verbose_name='Подчиняется аптеке'),
        ),
    ]
