# Generated by Django 5.2.4 on 2025-08-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0002_pharmacy_is_main_pharmacy_main_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является руководителем', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является заведующим аптекой', verbose_name='Заведующий'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Выберите аптеку из списка', null=True, on_delete=django.db.models.deletion.PROTECT, to='kadr.pharmacy', verbose_name='Аптека'),
        ),
    ]
